import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="container mx-auto h-[calc(100vh-7rem)] flex justify-center items">
          {children}
        </main>
      </body>
    </html>
  );
}
